#!/usr/bin/perl -w
use strict;

my ($src, $tgt, $al) = @ARGV;

sub makeEpsArray {
  my @toks = map { "($_)" } reverse split " ", $_[0];
  push @toks, "()";
  "[@toks]";
}

sub makeEpsAlignment {
  my $a = shift;
  $a =~ s/(\d+)-(\d+)/[$1 $2]/g;
  "[$a]";
}

my $f = makeEpsArray $src;
my $e = makeEpsArray $tgt;
my $a = makeEpsAlignment $al;

print <<HEAD
%!PS-Adobe EPSF-3

/French
$f
def
/English
$e
def
/Alignment
$a
def
HEAD
